### ISSUE TITLE
Can't build test env on Fedora34 need help.

### ISSUE THREAD

**Issue by FineFan** [sid-project/sid#98] opened 2021-03-31 13:00 UTC

**Comment by FineFan** [comment] 2021-03-31 13:04
Hi Peter,

Recently we (kernel storage) need to start SID testing, but I have a problem on build a test env  (Fedora34 server install sid rpms)
Here is logs please help:

Fedora-Server-dvd-x86_64-34_Beta-1.3.iso


[root@fedora34b13 ~]# rpm -qa | grep ^sid
sid-base-libs-0.0.4-4.fc34.x86_64
sid-log-libs-0.0.4-4.fc34.x86_64
sid-iface-libs-0.0.4-4.fc34.x86_64
sid-resource-libs-0.0.4-4.fc34.x86_64
sid-tools-0.0.4-4.fc34.x86_64
sid-0.0.4-4.fc34.x86_64
sid-mod-dummies-0.0.4-4.fc34.x86_64
sid-mod-block-dm-mpath-0.0.4-4.fc34.x86_64
sid-mod-block-blkid-0.0.4-4.fc34.x86_64
[root@fedora34b13 ~]# cat /proc/cmdline  
BOOT_IMAGE=(hd0,msdos1)/vmlinuz-5.11.3-300.fc34.x86_64 root=/dev/mapper/fedora_top--server--hp-root ro rd.lvm.lv=fedora_top-server-h
p/root sid.enabled=1
[root@fedora34b13 ~]#

[root@fedora34b13 ~]# sid -f
<module/blkid.so> Failed to open module: /usr/lib64/sid/modules/ucmd/block/blkid.so: undefined symbol: blkid_type_lookup.
<module-registry/block> Failed to preload module /usr/lib64/sid/modules/ucmd/block/blkid.so.
<dm_mpath> failed to initialize mpathvalid
<module/dm_mpath.so> Module-specific initialization failed.
<module-registry/block> Failed to preload module /usr/lib64/sid/modules/ucmd/block/dm_mpath.so.



[root@fedora34b13 ~]# systemctl restart sid
Job for sid.service failed because the control process exited with error code.
See "systemctl status sid.service" and "journalctl -xeu sid.service" for details.
[root@fedora34b13 ~]# systemctl  status  sid
× sid.service - Storage Instantiation Daemon
    Loaded: loaded (/usr/lib/systemd/system/sid.service; static)
    Active: failed (Result: exit-code) since Wed 2021-03-31 20:39:25 CST; 9s ago
   Process: 1273 ExecStart=/usr/sbin/sid -f (code=exited, status=1/FAILURE)
  Main PID: 1273 (code=exited, status=1/FAILURE)
       CPU: 7ms

3月 31 20:39:25 fedora34b13 sid[1273]: <module-registry/block> Failed to preload module /usr/lib64/sid/modules/ucmd/block/blkid.so.
3月 31 20:39:25 fedora34b13 sid[1273]: <dm_mpath> failed to initialize mpathvalid
3月 31 20:39:25 fedora34b13 sid[1273]: <module/dm_mpath.so> Module-specific initialization failed.
3月 31 20:39:25 fedora34b13 sid[1273]: <module-registry/block> Failed to preload module /usr/lib64/sid/modules/ucmd/block/dm_mpath.>
3月 31 20:39:25 fedora34b13 sid[1273]: <ubridge> Failed to create local server socket: Address already in use.
3月 31 20:39:25 fedora34b13 sid[1273]: <ubridge> Failed to set up local server socket.
3月 31 20:39:25 fedora34b13 sid[1273]: <sid> Failed to create udev bridge interface.
3月 31 20:39:25 fedora34b13 systemd[1]: sid.service: Main process exited, code=exited, status=1/FAILURE
3月 31 20:39:25 fedora34b13 systemd[1]: sid.service: Failed with result 'exit-code'.
3月 31 20:39:25 fedora34b13 systemd[1]: Failed to start Storage Instantiation Daemon.

**Comment by bmarzins** [comment] 2021-03-31 16:14
So `sid -f` did start SID the first time. Only the `systemctl restart sid` failed. Correct? I assume that the original sid process is still running, given the binding failures, and systemd isn't smart enough to stop it, if it didn't start it. If you start SID the first time via systemd does everything work correctly? Also, I assume the multipath errors are because device-mapper-multipath is not installed. Is that true?

**Comment by prajnoha** [comment] 2021-03-31 18:56
There's `undefined symbol: blkid_type_lookup` which took my attention. When I looked at the build logs, it looks it's caused by `gperf` missing as builddep in the spec file. I'm not yet sure why mpathvalid failed though, will need to check... (when I build from sources, that one works).

**Comment by FineFan** [comment] 2021-04-01 04:28
I would like to add more detail here.
What I am going to do is to set up a SID test suit.
    My plan is: 
    A. Set  up a test env and confirm that SID is working normally on the OS.
    B. Doing some device change as the final user always do like: add /remove/modify/query  block device(like sda ,vda,nvme,etc) and other device(lvm,etc)to see if SID is working normally.

Now I am stuck at step A, I can't sure what I did is the right steps , so I add more detail here:
1. I download the Fedora34 server from :
http://download.eng.pek2.redhat.com/released/fedora/F-34/Beta/Server/x86_64/iso/Fedora-Server-dvd-x86_64-34_Beta-1.3.iso
2. After install it on my desktop workstation.
I use dnf -y install sid* to install sid related rpms which from the default repo come with the OS.
3. Add kernel command line option with grubby as below:
```shell
 grubby --update-kernel /boot/vmlinuz-5.11.3-300.fc34.x86_64 --args="sid.enabled=1"
```
4.Reboot the machine then to take a look what I could do here:
4.1 Check the kernel command line parameter is here with below command:
```shell
 cat /proc/cmdline
    BOOT_IMAGE=(hd0,msdos1)/vmlinuz-5.11.3-300.fc34.x86_64 root=/dev/mapper/fedora_top--server--hp-root ro rd.lvm.lv=fedora_top-server-hp/root sid.enabled=1
```
     It has "sid.enabled=1" in the end so I think: "ok it work with SID now".
4.2 I saw the rpm "sid-0.0.4-4.fc34.x86_64" install a command  /usr/sbin/sid, so I am going to paly with it, first thing first is to play with it's options one by one:
```shell
[root@fedora34b13 ~]# sid --help
Usage: sid [options]

    -f|--foreground  Run in foreground.
    -h|--help        Show this help information.
    -v|--verbose     Verbose mode, repeat to increase level.
    -V|--version     Show SID version.
```
as you can see the "--help" works. then the "-f"

```shell
[root@fedora34b13 ~]# sid -f
<module/blkid.so> Failed to open module: /usr/lib64/sid/modules/ucmd/block/blkid.so: undefined symbol: blkid_type_lookup.
<module-registry/block> Failed to preload module /usr/lib64/sid/modules/ucmd/block/blkid.so.
<dm_mpath> failed to initialize mpathvalid
<module/dm_mpath.so> Module-specific initialization failed.
<module-registry/block> Failed to preload module /usr/lib64/sid/modules/ucmd/block/dm_mpath.so.


^C[root@fedora34b13 ~]#
```
It give out some error output, then hang there.
I created a new partation nothing there, 
So now I am think: "ok maybe it is NOT  work with SID well now". let's asking for help.
So please help:
1. Am I on the right steps on setup a test env?
2. Which tools  could help us to see what happen there? udev tools?
3. Can we hold some Google meeting to discuss more detail?

**Comment by prajnoha** [comment] 2021-04-01 08:05
> 1. I download the Fedora34 server from :
>    http://download.eng.pek2.redhat.com/released/fedora/F-34/Beta/Server/x86_64/iso/Fedora-Server-dvd-x86_64-34_Beta-1.3.iso
> 2. After install it on my desktop workstation.
>    I use dnf -y install sid* to install sid related rpms which from the default repo come with the OS.
> 3. Add kernel command line option with grubby as below:
> 
> ```shell
>  grubby --update-kernel /boot/vmlinuz-5.11.3-300.fc34.x86_64 --args="sid.enabled=1"
> ```
> 

The `sid.*`  on kernel command line is currently not used because the systemd socket/service is disabled by default... We will use that later. You only need to enable the `sid.socket` (`systemd enable --now sid.socket`) and the `sid.service` should start automatically by systemd as soon as there's request on the socket (so you don't need to enable/start the `sid.service` itself).

> 4.Reboot the machine then to take a look what I could do here:
> 4.1 Check the kernel command line parameter is here with below command:
> 
> ```shell
>  cat /proc/cmdline
>     BOOT_IMAGE=(hd0,msdos1)/vmlinuz-5.11.3-300.fc34.x86_64 root=/dev/mapper/fedora_top--server--hp-root ro rd.lvm.lv=fedora_top-server-hp/root sid.enabled=1
> ```
> 
> It has "sid.enabled=1" in the end so I think: "ok it work with SID now".
> 
> 4.2 I saw the rpm "sid-0.0.4-4.fc34.x86_64" install a command /usr/sbin/sid, so I am going to paly with it, first thing first is to play with it's options one by one:
> 
> ```shell
> [root@fedora34b13 ~]# sid --help
> Usage: sid [options]
> 
>     -f|--foreground  Run in foreground.
>     -h|--help        Show this help information.
>     -v|--verbose     Verbose mode, repeat to increase level.
>     -V|--version     Show SID version.
> ```
> 
> as you can see the "--help" works. then the "-f"
> 
> ```shell
> [root@fedora34b13 ~]# sid -f
> <module/blkid.so> Failed to open module: /usr/lib64/sid/modules/ucmd/block/blkid.so: undefined symbol: blkid_type_lookup.
> <module-registry/block> Failed to preload module /usr/lib64/sid/modules/ucmd/block/blkid.so.
> <dm_mpath> failed to initialize mpathvalid
> <module/dm_mpath.so> Module-specific initialization failed.
> <module-registry/block> Failed to preload module /usr/lib64/sid/modules/ucmd/block/dm_mpath.so.
> 

You need to choose here - either:

  - You'll have the SID daemon started by systemd (by enabling the `sid.socket` service as described above).
  
  -  Or you keep the `sid.socket` and `sid.service` stopped and disabled and instead you run `sid` directly from command line.

To see more debug output, you can switch into verbose mode:

  - If you go through the official `sid.socket/service`, you can set `VERBOSE=<verbose_level_number>` (highest verbose level number at the moment is 4) in `/etc/sysconfig/sid.sysconfig`. Then you can check the output through the usual `journalctl` means (`journalctl -u sid`).

  - If you run `sid` directly from command line, you can switch verbose mode with repeating `-v` (up to 4 times).

Important is that you can't have both - either you disable/stop the systemd way and use direct way or vice versa.

> 
> ^C[root@fedora34b13 ~]#
> ```
> 
> It give out some error output, then hang there.

It's waiting for requests. The requests are done by `usid` command called from `/usr/lib/udev/rules.d/00-sid.rules` (this way we handle incoming uevents for block devices) or by using `sidctl` command (which is newer I think and we need to update the pacakge to pick this new command. So I need to provide you updated packages!)

> I created a new partation nothing there,

You need verbose output to see more, otherwise, the daemon is quiet (only prints warnings and errors).

**Comment by prajnoha** [comment] 2021-04-01 08:12
We have quite a number of fixes upstream so I'll do a release and provide you new packages. These will also have the new `sidctl` command that provides better way of insight into sid's state.

**Comment by prajnoha** [comment] 2021-04-06 13:03
So I've done a new release and included that in a new rawhide package (https://koji.fedoraproject.org/koji/taskinfo?taskID=65305537). Should appear in the rawhide repo soon...

**Comment by trgill** [comment] 2021-06-29 14:08
@FineFan checking in to make sure you've got what you need?  Ok to close this issue?

**Comment by prajnoha** [comment] 2021-06-30 07:25
Yes, we can close this now...

**Closed by prajnoha** 2021-06-30 07:25 UTC
